export interface Category {
  id: string;
  name: string;
  description: string;
  keywords: string[];
}

export const categories: Category[] = [
  {
    id: "scripting_basics",
    name: "Scripting Basics",
    description: "Fundamental Angelscript actor and component patterns",
    keywords: [
      "class",
      "UCLASS",
      "UPROPERTY",
      "UFUNCTION",
      "BeginPlay",
      "Tick",
      "actor",
      "component",
      "DefaultComponent",
      "BlueprintOverride",
      "BlueprintEvent",
      "spawning",
      "constructor",
      "AActor",
      "UActorComponent",
      "SetupAttachment",
      "RootComponent",
      "Scene",
      "StaticMesh",
      "placing",
      "level",
      "blueprint",
    ],
  },
  {
    id: "language_fundamentals",
    name: "Language Fundamentals",
    description: "Core language features, types, and syntax",
    keywords: [
      "types",
      "int",
      "float",
      "FString",
      "FName",
      "FText",
      "TArray",
      "TMap",
      "TSet",
      "handle",
      "auto",
      "mixin",
      "delegate",
      "lambda",
      "cast",
      "Cast",
      "enum",
      "struct",
      "const",
      "reference",
      "namespace",
      "bool",
      "uint",
      "double",
      "container",
      "literal",
      "format",
      "interpolation",
      "primitive",
      "vector",
      "rotator",
      "transform",
    ],
  },
  {
    id: "properties_events",
    name: "Properties & Events",
    description: "Property specifiers, accessors, delegates, and event handling",
    keywords: [
      "UPROPERTY",
      "EditAnywhere",
      "BlueprintReadWrite",
      "Category",
      "Replicated",
      "delegate",
      "event",
      "timer",
      "input",
      "accessor",
      "property",
      "specifier",
      "EditDefaultsOnly",
      "VisibleAnywhere",
      "metadata",
      "NotReplicated",
      "NotEditable",
      "SetTimer",
      "ClearTimer",
      "Multicast",
      "Dynamic",
      "BindUFunction",
    ],
  },
  {
    id: "networking",
    name: "Networking",
    description: "Replication, RPC, and multiplayer scripting",
    keywords: [
      "replication",
      "replicated",
      "RPC",
      "Server",
      "Client",
      "NetMulticast",
      "NetFunction",
      "ReplicationCondition",
      "NetRole",
      "authority",
      "network",
      "multiplayer",
      "COND_",
      "HasAuthority",
      "IsNetMode",
      "bReplicates",
      "reliable",
      "unreliable",
      "autonomous",
      "simulated",
      "role",
    ],
  },
  {
    id: "testing",
    name: "Testing",
    description: "Unit tests, integration tests, and test commandlets",
    keywords: [
      "Test_",
      "FUnitTest",
      "Assert",
      "AreEqual",
      "IsTrue",
      "commandlet",
      "AngelscriptTest",
      "integration",
      "latent",
      "coverage",
      "testing",
      "unit",
      "IsFalse",
      "AreNotEqual",
      "IsNull",
      "IsNotNull",
      "TestEqual",
      "TestTrue",
      "TestFalse",
      "LatentCommand",
    ],
  },
  {
    id: "bindings",
    name: "C++ Bindings",
    description: "Creating C++ to Angelscript bindings and mixins",
    keywords: [
      "Bind_",
      "FUNC",
      "METHOD",
      "METHODPR",
      "ScriptMixin",
      "mixin",
      "StaticJIT",
      "JIT",
      "precompiled",
      "automatic",
      "binding",
      "FUNCPR",
      "FAngelscriptBinds",
      "RegisterFunction",
      "RegisterMethod",
      "asCObjectType",
      "asIScriptEngine",
      "asIScriptFunction",
      "FunctionLibrary",
      "AngelscriptBinds",
    ],
  },
  {
    id: "advanced_features",
    name: "Advanced Features",
    description: "Hot reload, preprocessor, GAS, Enhanced Input, and editor scripting",
    keywords: [
      "hot reload",
      "preprocessor",
      "#if",
      "EDITOR",
      "GAS",
      "GameplayAbility",
      "Enhanced Input",
      "subsystem",
      "function library",
      "editor script",
      "GameplayEffect",
      "AttributeSet",
      "AbilitySystemComponent",
      "InputAction",
      "InputMappingContext",
      "WITH_EDITOR",
      "TEST",
      "UScriptSubsystem",
      "metadata",
      "pragma",
    ],
  },
];

export function getCategoryById(id: string): Category | undefined {
  return categories.find((cat) => cat.id === id);
}
